version: '2'
services:
  db:
    image: postgres
  nginx:
    build: docker/nginx
    depends_on:
      - django
    ports:
      - "80:80"
  redis:
    image: redis:3.0
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: bash /django-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint:  bash /celery-entrypoint.sh
    command: beat
    depends_on:
      - django
    volumes:
      - .:/code
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: bash /celery-entrypoint.sh
    command: worker
    depends_on:
      - django
    volumes:
      - .:/code
  celery_flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: bash /celery-entrypoint.sh
    command: flower
    depends_on:
      - django
    ports:
      - "5555:5555"
    volumes:
      - .:/code
