FROM python:3.5

MAINTAINER Rémy Greinhofer <remy.greinhofer@gmail.com>

# Create the directory containing the code.
RUN mkdir -p /code /requirements
WORKDIR /requirements

# Define environment variables.
ENV PYTHONUNBUFFERED 1
ENV DATABASE_URL postgres://postgres:postgres@db:5432/postgres

# Update the package list.
RUN apt-get update \

    # Install libgeos.
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \

    # Install postgresql client.
    postgresql-client-9.4 \

    # Cleaning up.
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy the requirements files.
COPY requirements/* /requirements/

# Install the pip packages.
RUN pip install -q -r local.txt

# Copy django entry point.
COPY docker/craigomatic/django-entrypoint.sh /

# Create unprivileged user for celery.
RUN adduser --disabled-password --gecos '' celery

# Copy celery worker entry point.
COPY docker/craigomatic/celery-entrypoint.sh /

# Change workdir.
WORKDIR /code
