# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(name='Item',
                               fields=[
                                   ('id', models.CharField(max_length=200,
                                                           primary_key=True,
                                                           serialize=False)),
                                   ('link', models.URLField()),
                                   ('post_date', models.DateTimeField()),
                                   ('pnr', models.CharField(max_length=200)),
                                   ('price', models.PositiveIntegerField()),
                                   ('title', models.CharField(max_length=200)),
                                   ('retrieved', models.DateTimeField(auto_now_add=True)),
                               ], ),
        migrations.CreateModel(name='Search',
                               fields=[
                                   ('id', models.AutoField(auto_created=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           verbose_name='ID')),
                                   ('server', models.CharField(max_length=200)),
                                   ('category', models.CharField(max_length=50)),
                                   ('has_pic', models.BooleanField(default=True)),
                                   ('min_ask', models.PositiveIntegerField(default=0)),
                                   ('max_ask', models.PositiveIntegerField(default=1000)),
                                   ('query', models.CharField(default='',
                                                              max_length=300)),
                                   ('tag', models.CharField(max_length=20)),
                                   ('custom_search_args', models.CharField(default='',
                                                                           max_length=300)),
                                   ('last_update', models.DateTimeField(auto_now=True)),
                               ], ),
        migrations.AddField(model_name='item',
                            name='search',
                            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='craigmine.Search'), ),
    ]
